backend:
  name: github
  repo: Oliveves/portfolio
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "projects"
    label: "포트폴리오 게시글"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "연도", name: "year", widget: "string"}
      - {label: "Scope", name: "scope", widget: "text"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "상세 이미지들", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}}